on:
    workflow_call:
        inputs:
            artifact-name:
                type: string
                required: true
                description: "The name of the artifact containing the deb to include"
        secrets:
            ELEMENT_BOT_TOKEN:
                required: true
            CF_R2_ACCESS_KEY_ID:
                required: true
            CF_R2_TOKEN:
                required: true
# Protect reprepro database using concurrency
concurrency: reprepro
jobs:
    reprepro:
        name: Deploy debian package
        environment: packages.element.io
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: ${{ inputs.artifact-name }}
                  path: dist

            - name: Find deb
              id: prepare
              run: |
                  deb="$(ls *.deb | tail -n1)"
                  echo "incoming=$deb" >> $GITHUB_OUTPUT
              working-directory: dist

            - name: Publish to packages.element.io
              uses: vector-im/packages.element.io@master
              with:
                  file: ${{ steps.prepare.outputs.incoming }}
                  github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  bucket-api: ${{ vars.CF_R2_S3_API }}
                  bucket-key-id: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
                  bucket-access-key: ${{ secrets.CF_R2_TOKEN }}
